(load "~/.emacs.d/plugins/use-package.el")
(load "~/.emacs.d/plugins/auto-complete.el")
(load "~/.emacs.d/plugins/css-mode.el")
(load "~/.emacs.d/plugins/evil.el")
(load "~/.emacs.d/plugins/evil-leader.el")
(load "~/.emacs.d/plugins/evil-magit.el")
(load "~/.emacs.d/plugins/magit.el")
;; (load "~/.emacs.d/plugins/exec-shell.el")
(load "~/.emacs.d/plugins/flycheck.el")
(load "~/.emacs.d/plugins/helm.el")
(load "~/.emacs.d/plugins/helm-projectile.el")
(load "~/.emacs.d/plugins/helm-ag.el")
(load "~/.emacs.d/plugins/js2-mode.el")
(load "~/.emacs.d/plugins/json-mode.el")
(load "~/.emacs.d/plugins/keychord.el")
(load "~/.emacs.d/plugins/prettier.el")
;; (load "~/.emacs.d/plugins/prettier-eslint.el")
(load "~/.emacs.d/plugins/projectile.el")
(load "~/.emacs.d/plugins/which-key.el")
(load "~/.emacs.d/plugins/escreen.el")
(load "~/.emacs.d/plugins/markdown-mode.el")
(load "~/.emacs.d/plugins/diminish.el")
(load "~/.emacs.d/plugins/visual-fill.el")
(load "~/.emacs.d/plugins/base16-theme.el")
(load "~/.emacs.d/plugins/org-mode.el")
;;(load "~/.emacs.d/plugins/rainbow-delimeters.el")
(load "~/.emacs.d/plugins/nord.el")
;; (load "~/.emacs.d/plugins/mocha.el")

(load "~/.emacs.d/plugins/go-mode.el")
(load "~/.emacs.d/plugins/vterm.el")
