ZSH_DISABLE_COMPFIX="true"
# Path to your oh-my-zsh installation.
export ZSH=/Users/danielflynn/.oh-my-zsh

alias up="cd .. && ls"
alias c="clear"
alias gc="git commit -am"
alias ga="git add ."
alias gs="git status"
alias gpo='git pull origin "$(git rev-parse --abbrev-ref HEAD)"'
alias kclean="find . -name '*.orig' -delete "
alias 💩="rm -rf ./node_modules && yarn install; bin/spring stop;"
alias die="(killall node ; killall gulp ; killall grunt ; killall php; killall telnet)"
alias dc="docker-compose"
alias 💥="dc stop && dc rm -f && dc build --no-cache"
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias be="bundle exec"
alias bear="bundle exec rake"
alias hass="ssh -i ~/.ssh/id_rsa root@hassio.local"

alias home="cd ~"
alias root="cd $(git root)"
alias back="cd -"

# I loathe this package, skip install anywhere it attempts
export HUSKY=0

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi
HOMEBREW_PREFIX="$(brew --prefix)"
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"


# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder
fpath=(~/.zsh/completions $fpath)
fpath+=("$(brew --prefix)/share/zsh/site-functions")

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git node npm brew docker rails ruby)

# User configuration
export PATH="$PATH:$HOME:$GOPATH/bin:$HOME/.rvm/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/usr/local/sbin:/sbin:/usr/local/git/bin"
export LANG=en_US.UTF-8

export PATH="$HOME/.yarn/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/mongodb@3.6/bin:$PATH"
export PATH="/usr/local/opt/node@8/bin:$PATH"
export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PATH="/usr/local/opt/node@10/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

# Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="$HOME/.rubies:$PATH"

# Chruby
source $HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh
source $HOMEBREW_PREFIX/opt/chruby/share/chruby/auto.sh

# Pure terminal
autoload -U promptinit; promptinit
prompt pure

# fnm
eval "$(fnm env --use-on-cd)"

# pnpm
export PNPM_HOME="/Users/daniel.flynn/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm endexport

