ZSH_DISABLE_COMPFIX="true"
# Path to your oh-my-zsh installation.
export ZSH=/Users/danielflynn/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME=""

alias up="cd .. && ls"
alias c="clear"
alias gc="git commit -am"
alias ga="git add ."
alias gs="git status"
alias gpo='git pull origin "$(git rev-parse --abbrev-ref HEAD)"'
alias kclean="find . -name '*.orig' -delete "
alias 💩="rm -rf ./node_modules && npm cache clean && npm install"
alias die="(killall node ; killall gulp ; killall grunt ; killall php; killall telnet)"
alias dc="docker-compose"
alias 💥="dc stop && dc rm -f && dc build --no-cache"
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias rs="rails server"
alias rg="rails g"
alias b="buffalo"
alias bp="buffalo plugins"
alias ls="exa"
alias be="bundle exec"
alias bear="bundle exec rake"
alias hass="ssh -i ~/.ssh/id_rsa root@hassio.local"



# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder
fpath=(~/.zsh/completions $fpath)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git node npm brew docker rails ruby)

# User configuration
export PATH="$PATH:$HOME:$GOPATH/bin:$HOME/.rvm/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/usr/local/sbin:/sbin:/usr/local/git/bin"
export LANG=en_US.UTF-8

# Pure terminal
source $ZSH/oh-my-zsh.sh
autoload -U promptinit; promptinit
prompt pure

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

if [ -f ~/.bash_profile ]; then
  source ~/.bash_profile
fi

export PATH="$HOME/.yarn/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/mongodb@3.6/bin:$PATH"
export PATH="/usr/local/opt/node@8/bin:$PATH"
export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PATH="/usr/local/opt/node@10/bin:$PATH"
export PATH="/usr/local/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# GO
export GOPATH="${HOME}/.go"
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="$HOME/.rubies:$PATH"

# Auto load ruby from chruby
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh


export LDFLAGS="-L/usr/local/opt/postgresql@12/lib"
export CPPFLAGS="-I/usr/local/opt/postgresql@12/include"
export PKG_CONFIG_PATH="/usr/local/opt/postgresql@12/lib/pkgconfig"
export PATH="/usr/local/opt/postgresql@12/bin:$PATH"
